import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :investment_wallet, InvestmentWalletWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "bHT5ayMDe8arqIoOLi/yt1ptNskNWtiYIB+jQCtLRGqmxT7gH3JpSoVWmHChDEZ0",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:investment_wallet, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:investment_wallet, ~w(--watch)]}
  ]

string_envs = String.split(System.get_env("ENVIROMENTS_CONFIG", "|||"),"|")
# port = Enum.at(string_envs, 1) || System.get_env("PORT","4000")
pool_size = Enum.at(string_envs, 3) #|| System.get_env("DB_POOL", 10)
db_user_name = Enum.at(string_envs, 4) #|| System.get_env("DB_USERNAME","")
db_password = Enum.at(string_envs, 5) #|| System.get_env("DB_PASSWORD","")
db_hostname = Enum.at(string_envs, 6) #|| System.get_env("DATABASE_HOST","")
db_database = Enum.at(string_envs, 7) #|| System.get_env("DATABASE_DB_NAME","")
# db_maybe_ipv6 = Enum.at(string_envs, 8) #|| System.get_env("DB_MAYBE_IPV6",false)

db_url = "ecto://#{db_user_name}:#{db_password}@#{db_hostname}/#{db_database}"

  database_url = if(String.length(db_url) > 11, do: db_url, else:
      raise """
      environment variable DATABASE_URL is missing.
      For example: ecto://USER:PASS@HOST/DATABASE
      """)

config :investment_wallet, InvestmentWallet.Repo,
  # username: System.get_env("DATABASE_USER"),
  # password: System.get_env("DATABASE_PASSWORD"),
  # hostname: System.get_env("DATABASE_HOST"),
  # database: System.get_env("DATABASE_DB_NAME"),
  url: database_url,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :investment_wallet, InvestmentWalletWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/investment_wallet_web/router\.ex$",
      ~r"lib/investment_wallet_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :investment_wallet, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
